### ISSUE TITLE
"Error downloading map image from http://localhost:3002." In Tower cellar

### ISSUE THREAD

**Issue by Xdaci** [joffreybesos/d2-mapserver#1]
Just finished setting up my own server, and downloading/testing the maphack. It works brilliantly, better than og d2 maphack imo, I like the customization via settings. I did a nith run, and a baal run, no issues. Pretty excited as I cant imagine grinding the upcoming ladder without a working maphack. Then I decided to do a countess run, and sadly when I enter the tower cellar I get the title quoted error. I alt/tabbed out and restarted the server and the maphack and then it works, but as soon as I tele to and enter the next level, I get the same error. Shown here https://imgur.com/b55Pf9l

It says to refer to log.txt which shows these 
"2022-02-03 13-03-42: ERROR: Error downloading image from http://localhost:3002/v1/map/1265907283/2/24/image?wallthickness=1&edge=true
2022-02-03 13-03-48: ERROR: Could not load map image C:\Users\Curtis\AppData\Local\Temp\1265907283_2_24.png"

Any help would be greatly appreciated, thanks either way as I stated above the maphack is brilliant.

**Comment by Xdaci** [comment]
Did some more testing and it seems to be getting this error in other areas as well sadly. Arcane sanctuary, black marsh, also even in rogue encampment. So I'm assuming its something wrong with my d2 files maybe?

**Comment by joffreybesos** [comment]
Thanks for testing this, I've found the root cause, it was any level with a super chest. Not sure how I missed this bug.
Anyway I've just released beta 9 which resolves this issue https://github.com/joffreybesos/d2-mapserver/releases/tag/v9-beta
