### ISSUE TITLE
bladabindi backdoor?

### ISSUE THREAD

**Issue by StevenJamesWoodhouse** [joffreybesos/d2-mapserver#7]
Release is being flagged as containing the bladabindi backdoor trojan?

**Comment by joffreybesos** [comment]
I uploaded d2mapserver.exe to virustotal and got this https://www.virustotal.com/gui/file/5627828e11d44c0248694eca2e29aae89e911b7e8d16162fa0c46f7257e4bb4e/detection

Where are you getting bladabindi?

**Comment by StevenJamesWoodhouse** [comment]
Windows Defender

**Comment by StevenJamesWoodhouse** [comment]
Its the SetupServer.exe that was being flagged

**Comment by joffreybesos** [comment]
Ah, well here is the source code for serversetup.exe
https://github.com/joffreybesos/d2-mapserver/blob/master/src/ahk/serversetup.ahk

If you download that code, convert to EXE with Autohotkey, you'll likely get the same false positive
