### ISSUE TITLE
Missing resources to build docker image

### ISSUE THREAD

**Issue by mzarglis** [joffreybesos/d2-mapserver#8]
The dockerfile references 
```
COPY ./build/static/Roboto-Regular.ttf ./
COPY ./build/static/Roboto-Bold.ttf ./
COPY ./build/static/exocetblizzardot-medium.otf ./
```

 which are not included in the repo any chance you could include them so we can build container from source?

**Comment by joffreybesos** [comment]
They are in `src/static/` when you do a `npm run build` these static files will be copied into the `build/static` folder so they are bundled with the build files
